### ISSUE TITLE
NanoScrollPanelWidgetSet load failure

### ISSUE THREAD

**Issue by malcolmdavis** [hekailiang/nanoscrollpanel-vaadin-addon#3]
When doing a maven build, the build fails with:
GWT Module org.vaadin.hhe.nanoscrollpanel.gwt.NanoScrollPanelWidgetSet not found in project sources or resources.

The following is in the WeidgetSet.wgt.xml
<inherits name="org.vaadin.hhe.nanoscrollpanel.gwt.NanoScrollPanelWidgetSet" />

The build fails for Vaadin 7.3.6 and 7.3.8

```
    <dependency>
        <groupId>org.vaadin.addons</groupId>
        <artifactId>nanoscrollpanel</artifactId>
        <version>1.1.7</version>
    </dependency>
```

I have added and used add-ons in the past, but nanoscrollpanel is failing.

**Comment by malcolmdavis** [comment]
More details:

Clean maven project built using vaadin-archetype-application 7.3.6

Java version jdk1.7.0_67

Maven: 3.2.1

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.vaadin:vaadin-maven-plugin:7.3.6:compile (default) on project NanoScrollDemo: GWT Module org.vaadin.hhe.nanoscrollpanel.gwt.NanoScrollPanelWidgetSet not found in project sources or resources. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.vaadin:vaadin-maven-plugin:7.3.6:compile (default) on project NanoScrollDemo: GWT Module org.vaadin.hhe.nanoscrollpanel.gwt.NanoScrollPanelWidgetSet not found in project sources or resources.
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: GWT Module org.vaadin.hhe.nanoscrollpanel.gwt.NanoScrollPanelWidgetSet not found in project sources or resources.
    at org.codehaus.mojo.gwt.shell.CompileMojo.compilationRequired(CompileMojo.java:497)
    at org.codehaus.mojo.gwt.shell.CompileMojo.compile(CompileMojo.java:357)
    at org.codehaus.mojo.gwt.shell.CompileMojo.doExecute(CompileMojo.java:281)
    at org.codehaus.mojo.gwt.shell.AbstractGwtShellMojo.execute(AbstractGwtShellMojo.java:172)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
    ... 19 more
Caused by: org.codehaus.mojo.gwt.utils.GwtModuleReaderException: GWT Module org.vaadin.hhe.nanoscrollpanel.gwt.NanoScrollPanelWidgetSet not found in project sources or resources.
    at org.codehaus.mojo.gwt.AbstractGwtModuleMojo.readModule(AbstractGwtModuleMojo.java:214)
    at org.codehaus.mojo.gwt.GwtModule.getLocalInherits(GwtModule.java:189)
    at org.codehaus.mojo.gwt.GwtModule.getInherits(GwtModule.java:149)
    at org.codehaus.mojo.gwt.GwtModule.getEntryPoints(GwtModule.java:114)
    at org.codehaus.mojo.gwt.shell.CompileMojo.compilationRequired(CompileMojo.java:410)
    ... 24 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
1. &lt;inherits name=&quot;org.vaadin.hhe.nanoscrollpanel.gwt.NanoScrollPanelWidgetSet&quot; /&gt;  is inserted into AppWidgetSet.gwt.xml
2. There are no other add-ons or plugins outside of the defaults inserted by vaadin-archetype-application.
3. I'm using an external maven build and not the Eclipse build process, so the following ticket does not apply http://dev.vaadin.com/ticket/15500
4. I've made the tweak from vaadin-client-compiled to vaadin-client-compiler as suggested in stackoverflow with no success.
   http://stackoverflow.com/questions/27716171/error-when-to-compile-my-theme-with-vaadin-7-3-and-valo-theme
5. I do have success with other add-ons.

Thanks,
Malcolm

**Comment by hekailiang** [comment]
Can you try latest code from repository?

**Comment by malcolmdavis** [comment]
Downloaded latest code base, built, tested.  Everything works.

Thank you,
Malcolm

**Comment by Rifffi** [comment]
I run into the same problem when i use maven. I use maven 3.3.3 with Eclipse Mars 4.5.1 and Java 1.8.0_66. I found a problem with the auto generated _**_webWidgetset.gwt.xml.
When i run maven install the entry in the *_*_webWidgetset.gwt.xml changed the s from lowercase to uppercase. 
<inherits name="org.vaadin.hhe.nanoscrollpanel.gwt.NanoScrollPanelWidgetset" /> to
<inherits name="org.vaadin.hhe.nanoscrollpanel.gwt.NanoScrollPanelWidgetSet" />
I cloned the project from Git. Problem still exists. After this i changed all words and filenames from NanoScrollPanelWidgetset to NanoScrollPanelWidgetSet in the project. Then it works for me.
Thanks,
Riffi
